import './src/styles/globals.css';
import 'font-awesome/css/font-awesome.min.css';
import 'elegant-icons/style.css';
import 'et-line/style.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.js';
import "./src/styles/animated.css";
import './src/styles/style.scss';
import './src/styles/style_grey.scss';
export { default as wrapRootElement } from "./src/wrapRootElement";
